name: Deploy to Maven Central

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Solo tags como 1.2.3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necesario para poder verificar el commit del tag y comparar con master

    - name: Verify tag points to latest commit on master
      run: |
        TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
        MASTER_COMMIT=$(git rev-parse origin/master)
        echo "Tag commit: $TAG_COMMIT"
        echo "Master commit: $MASTER_COMMIT"
        if [ "$TAG_COMMIT" != "$MASTER_COMMIT" ]; then
          echo "The tag does not point to the last master commit. Aborting deployment."
          exit 1
        fi

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
        server-id: intino-sonatype
        server-username:  MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Deploy to Maven Central
      run: mvn -f pom.xml clean deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} --batch-mode
