name: Deploy to Maven Central

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch master history
        run: git fetch origin master

      - name: Verify tag points to latest commit on master
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          MASTER_COMMIT=$(git rev-parse origin/master)
          echo "Tag commit: $TAG_COMMIT"
          echo "Master commit: $MASTER_COMMIT"
          if [ "$TAG_COMMIT" != "$MASTER_COMMIT" ]; then
            echo "Tag does not point to latest master commit. Aborting."
            exit 1
          fi

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          KEY_ID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d: -f5)
          echo "GPG_KEYNAME=$KEY_ID" >> $GITHUB_ENV

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>intino-sonatype</id>
                <username>${{ secrets.MAVEN_USERNAME }}</username>
                <password>${{ secrets.MAVEN_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to Maven Central
        run: |
          mvn clean deploy --batch-mode \
            -Dgpg.keyname=${{ env.GPG_KEYNAME }} \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}